language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t stevenparrott/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true stevenparrott/docker-react npm run test